[package]
name = "eyes-of-hell"
version = "0.1.0"
edition = "2021"

[dependencies]
three-d = { version = "0.18.2" }
functor_derive = "0.4.3"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
wasm-bindgen = "0.2.100"
