name: Upload multi-platform release to Itch
on: ["workflow_dispatch"]

env:
  CARGO_BUILD: cargo build --release --bin eyes-of-hell

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache etc. for Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' 
      - name: Cache for Cargo
        uses: actions/cache@v4
        env:
          platform: web
        with:
          path: target/*/dist
          key: ${{ env.platform }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ env.platform }}
      - name: Install Node dependencies
        run: npx pnpm i
      - name: Build webpack
        run: npm run release
      - name: Save /dist as artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: butler-web-build
          path: dist
          retention-days: 1
          if-no-files-found: error
          overwrite: true

  bin:
    strategy:
      matrix:
        profile:
          - os: windows-latest
            platform: win
            ext: .exe
          - os: ubuntu-latest
            platform: linux-x86
          - os: ubuntu-24.04-arm
            platform: linux-arm
          - os: macos-13
            platform: mac-x86
          - os: macos-latest
            platform: mac-arm
    runs-on: ${{ matrix.profile.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: target/*/dist
          key: ${{ matrix.profile.platform }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ matrix.profile.platform }}-
      - name: Build ${{ matrix.profile.ext || 'executable' }} for ${{ matrix.profile.platform }}
        run: $CARGO_BUILD
        shell: bash
      - name: Save eyes-of-hell${{ matrix.profile.ext }} as artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: butler-${{ matrix.profile.platform }}-build
          path: target/release/eyes-of-hell.exe${{ matrix.profile.ext }}
          retention-days: 1
          if-no-files-found: error
          overwrite: true
        
  upload-everything:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - platform: web
          - platform: win
            ext: .exe
            channel: windows
            suffix: win-x86-
          - platform: linux-x86
            suffix: linux-x86-
          - platform: linux-arm
            suffix: linux-arm
          - platform: mac-x86
            suffix: macos-x86-
          - platform: mac-arm
            suffix: macos-arm
    needs: ["web", "bin"]
    steps:
    
      - name: Retrieve web build as artifact
        uses: actions/download-artifact@v4
        with:
          name: butler-web-build
          path: web
          latest: true
      - name: Upload web build to itch.io
        uses: yeslayla/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_BUTLER_CREDS }}
          ITCH_USER: unrelatedstring
          ITCH_GAME: eyes-of-hell
          PACKAGE: web
          CHANNEL: web
          
      - name: Retrieve ${{ matrix.profile.platform }} build as artifact
        uses: actions/download-artifact@v4
        with:
          name: butler-${{ matrix.profile.platform }}-build
          path: ${{ matrix.profile.platform }}
          latest: true
      - name: Rename eyes-of-hell.exe to eyes-of-hell_win-x86-64.exe
        if: ${{ matrix.profile.suffix }}
        run: mv ${{ matrix.profile.platform }}/eyes-of-hell${{ matrix.profile.ext }} ${{ matrix.profile.platform }}/eyes-of-hell_${{ matrix.profile.suffix }}64${{ matrix.profile.ext }}
      - name: Upload ${{ matrix.profile.channel || matrix.profile.platform }} build to itch.io
        uses: yeslayla/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_BUTLER_CREDS }}
          ITCH_USER: unrelatedstring
          ITCH_GAME: eyes-of-hell
          PACKAGE: ${{ matrix.profile.platform }}
          CHANNEL: ${{ matrix.profile.channel || matrix.profile.platform }}
          
      - name: Clean up transient artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: butler-**
