name: CI
on: ["push"]

env:
  CARGO_BUILD: cargo build --release --bin eyes-of-hell

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache etc. for Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' 
      - name: Cache for Cargo
        uses: actions/cache@v4
        env:
          platform: web
        with:
          path: target/*/dist
          key: ${{ env.platform }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ env.platform }}
      - name: Install Node dependencies
        run: npx pnpm i
      - name: Build webpack
        run: npm run release

  bin:
    strategy:
      matrix:
        profile:
          - os: windows-latest
            platform: win
          - os: ubuntu-latest
            platform: linux-x86
          - os: ubuntu-24.04-arm
            platform: linux-arm
          - os: macos-13
            platform: mac-x86
          - os: macos-latest
            platform: mac-arm
    runs-on: ${{ matrix.profile.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: target/*/dist
          key: ${{ matrix.profile.platform }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ matrix.profile.platform }}-
      - name: Build ${{ matrix.profile.platform }} executable
        run: $CARGO_BUILD
        shell: bash
